# Generated by Django 5.2.7 on 2025-12-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='posts', to='api.track'),
        ),
    ]
